apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker-0
  name: kafka-service-0
  namespace: myproject
spec:
  ports:
  - port: 9092
  selector:
    app: kafka-broker-0
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker-1
  name: kafka-service-1
  namespace: myproject
spec:
  ports:
  - port: 9092
  selector:
    app: kafka-broker-1
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker-0
  name: kafka-broker-0
  namespace: myproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-0
  template:
    metadata:
      labels:
        app: kafka-broker-0
    spec:
      hostname: kafka-broker-0
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-broker-0:9092
        - name: KAFKA_CREATE_TOPICS
          value: mytopicadriel:2:2
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: kafka-broker-0
        ports:
        - containerPort: 9092

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker-1
  name: kafka-broker-1
  namespace: myproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-1
  template:
    metadata:
      labels:
        app: kafka-broker-1
    spec:
      hostname: kafka-broker-1
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-broker-1:9092
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: kafka-broker-1
        ports:
        - containerPort: 9092